### ISSUE TITLE
Proxy Format?

### ISSUE THREAD

**Issue by tuffboy807** [martinvigo/email2phonenumber#15]
What am I doing wrong? like any fix for this?
I got no clue but my log is
Traceback (most recent call last):
  File "email2phonenumber.py", line 1070, in <module>
    set_proxy_list()
  File "email2phonenumber.py", line 961, in set_proxy_list
    proxy_list_not_formatted = file_content.split("\n")
AttributeError: 'filter' object has no attribute 'split'

**Comment by martinvigo** [comment]
You need to provide a list of proxy IPs as a dictionary
