### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by andre-santos1** [martinvigo/email2phonenumber#35]
When I run python3 `email2phonenumber.py scrape -e target@email.com` the script yields the following error:

Starting scraping online services...

Scraping Ebay...

Traceback (most recent call last):

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn

    conn = connection.create_connection(

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/util/connection.py", line 72, in create_connection

    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):

  File "/home/osint/.pyenv/versions/3.9.0/lib/python3.9/socket.py", line 953, in getaddrinfo

    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen

    httplib_response = self._make_request(

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request

    self._validate_conn(conn)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn

    conn.connect()

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect

    self.sock = conn = self._new_conn()

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn

    raise NewConnectionError(

urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fb3fcc60ac0>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/requests/adapters.py", line 489, in send

    resp = conn.urlopen(

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen

    retries = retries.increment(

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment

    raise MaxRetryError(_pool, url, error or ResponseError(cause))

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fyp.ebay.com', port=443): Max retries exceeded with url: /EnterUserInfo?ru=https%3A%2F%2Fwww.ebay.com%2F&gchru=&clientapptype=19&rmvhdr=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3fcc60ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumber/email2phonenumber.py", line 1019, in <module>

    start_scrapping(args.email, args.quiet)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumber/email2phonenumber.py", line 538, in start_scrapping

    scrape_ebay(email)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumber/email2phonenumber.py", line 625, in scrape_ebay

    response = session.get(

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/requests/sessions.py", line 600, in get

    return self.request("GET", url, **kwargs)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/requests/sessions.py", line 587, in request

    resp = self.send(prep, **send_kwargs)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/requests/sessions.py", line 701, in send

    r = adapter.send(request, **kwargs)

  File "/home/osint/Programas/email2phonenumberEnvironment/email2phonenumberEnvironment/lib/python3.9/site-packages/requests/adapters.py", line 565, in send

    raise ConnectionError(e, request=request)

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fyp.ebay.com', port=443): Max retries exceeded with url: /EnterUserInfo?ru=https%3A%2F%2Fwww.ebay.com%2F&gchru=&clientapptype=19&rmvhdr=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb3fcc60ac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by KrentosAtos** [comment]
I have same problems, the problem is domain fyp.ebay.com doesn't exist for several reasons, try to `ping fyp.ebay.com` on terminal and it say unknown host. What I do is comment the scrape_ebay(email) in function start_scrapping.

**Comment by kybrbie** [comment]
I don't understand at all...I'm having the same issues, can someone please explain in a little better detail how to fix this...
