### ISSUE TITLE
That tool just gives errors

### ISSUE THREAD

**Issue by bashinho** [martinvigo/email2phonenumber#37]
Starting scraping online services...
Scraping Ebay...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 700, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1017, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f06749c7760>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 756, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='fyp.ebay.com', port=443): Max retries exceeded with url: /EnterUserInfo?ru=https%3A%2F%2Fwww.ebay.com%2F&gchru=&clientapptype=19&rmvhdr=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f06749c7760>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bashinho/GIT/email2phonenumber/email2phonenumber.py", line 1019, in <module>
    start_scrapping(args.email, args.quiet)
  File "/home/bashinho/GIT/email2phonenumber/email2phonenumber.py", line 538, in start_scrapping
    scrape_ebay(email)
  File "/home/bashinho/GIT/email2phonenumber/email2phonenumber.py", line 625, in scrape_ebay
    response = session.get(
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fyp.ebay.com', port=443): Max retries exceeded with url: /EnterUserInfo?ru=https%3A%2F%2Fwww.ebay.com%2F&gchru=&clientapptype=19&rmvhdr=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f06749c7760>: Failed to establish a new connection: [Errno -2] Name or service not known'))

**Comment by cheetahbyte** [comment]
hey there :wave: 
the problem is that the ebay site `fyp.ebay.com`, which it's trying to scrape, does not exist anymore. However you can still scrape PayPal and LastPass if you uncomment line #538, which disables ebay scraping.

**Comment by kybrbie** [comment]
How do you uncomment a line? Like what do you have to do...

**Comment by DaniyarNauryz** [comment]
> hey there 👋 the problem is that the ebay site `fyp.ebay.com`, which it's trying to scrape, does not exist anymore. However you can still scrape PayPal and LastPass if you uncomment line #538, which disables ebay scraping.

Several valid email addresses -- corporate and public ones -- return this:

Starting scraping online services...
Scraping Lastpass...
←[93mLastpass did not report any digits ←[0m
Scraping Paypal...
←[93mPaypal did not report any digits ←[0m

**Comment by cheetahbyte** [comment]
Maybe it's just not able to find any information based on the emails you provided. However this is something you can test manually, if you follow the steps the code is taking.

**Comment by bxnxans** [comment]
> hey there 👋 the problem is that the ebay site `fyp.ebay.com`, which it's trying to scrape, does not exist anymore. However you can still scrape PayPal and LastPass if you uncomment line #538, which disables ebay scraping.

how do you uncomment this line?

**Comment by cheetahbyte** [comment]
@bxnxans  You can just put a `#` in front of it.

**Comment by tbusman** [comment]
I disabled the command and it still went to ebay. How do I stop it completely from going to ebay?

**Comment by cheetahbyte** [comment]
@tbusman Are you sure, you put a `#` in front of the line 538? Commenting this line will definitely stop it from using ebay, as it will prevent the function call.

**Comment by tbusman** [comment]
> [@tbusman](https://github.com/tbusman) Are you sure, you put a `#` in front of the line 538? Commenting this line will definitely stop it from using ebay, as it will prevent the function call.

I did, and it still tried to scrape eBay.

**Comment by cheetahbyte** [comment]
Can you provide the error? @tbusman

**Comment by tbusman** [comment]
It’s the same error message in the post. I have uncommented it out many times and have deleted the comment itself, as well as deleted the function with it and it still scrapes ebay when running the program.

**Comment by tbusman** [comment]
> Can you provide the error? [@tbusman](https://github.com/tbusman)

here is the code. Yes it is commented out.

──(kali㉿kali)-[~/Downloads/email2phonenumber-master]
└─$ python2 email2phonenumber.py scrape -e thebusman2000@gmail.com
Starting scraping online services...
Scraping Ebay...
Traceback (most recent call last):
  File "email2phonenumber.py", line 1019, in <module>
    start_scrapping(args.email, args.quiet)
  File "email2phonenumber.py", line 538, in start_scrapping
    scrape_ebay(email)
  File "email2phonenumber.py", line 637, in scrape_ebay
    verify=verifyProxy
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 543, in get
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 530, in request
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/sessions.py", line 643, in send
  File "/usr/share/offsec-awae-wheels/requests-2.23.0-py2.py3-none-any.whl/requests/adapters.py", line 516, in send
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='fyp.ebay.com', port=443): Max retries exceeded with url: /EnterUserInfo?ru=https%3A%2F%2Fwww.ebay.com%2F&gchru=&clientapptype=19&rmvhdr=false (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f5595afad10>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by cheetahbyte** [comment]
@tbusman I've created a fork of this repo which entirely removes the ebay part. Maybe give that a try [https://github.com/cheetahbyte/email2phonenumber](https://github.com/cheetahbyte/email2phonenumber).
