### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by pretech86** [martinvigo/email2phonenumber#9]
when i try ./email2phonenumber scrap -e MY_EMAIL i get this error 

/usr/local/lib/python2.7/dist-packages/bs4/element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.

  'The soupsieve package is not installed. CSS selectors cannot be used.'

Traceback (most recent call last):

  File "./email2phonenumber.py", line 12, in <module>

    from bs4 import BeautifulSoup

  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 34, in <module>

    from .builder import builder_registry, ParserRejectedMarkup

  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 7, in <module>

    from bs4.element import (

  File "/usr/local/lib/python2.7/dist-packages/bs4/element.py", line 19, in <module>

    from bs4.formatter import (

  File "/usr/local/lib/python2.7/dist-packages/bs4/formatter.py", line 1, in <module>

    from bs4.dammit import EntitySubstitution

  File "/usr/local/lib/python2.7/dist-packages/bs4/dammit.py", line 52, in <module>

    class EntitySubstitution(object):

  File "/usr/local/lib/python2.7/dist-packages/bs4/dammit.py", line 82, in EntitySubstitution

    CHARACTER_TO_HTML_ENTITY_RE) = _populate_class_variables()

  File "/usr/local/lib/python2.7/dist-packages/bs4/dammit.py", line 68, in _populate_class_variables

    character = chr(codepoint)

ValueError: chr() arg not in range(256)

and when i try python3 emial2phonenumber.py i get this error 

usage: email2phonenumber.py [-h] {scrape,generate,bruteforce} ...

email2phonenumber.py: error: invalid choice: 'scrap' (choose from 'scrape', 'generate', 'bruteforce')

**Comment by martinvigo** [comment]
It's not scrap, it's scrape as the error message says
